// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package serverconfig

import (
	mock "github.com/stretchr/testify/mock"
)

// NewReferenceReporterMock creates a new instance of ReferenceReporterMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReferenceReporterMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReferenceReporterMock {
	mock := &ReferenceReporterMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ReferenceReporterMock is an autogenerated mock type for the ReferenceReporter type
type ReferenceReporterMock struct {
	mock.Mock
}

type ReferenceReporterMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ReferenceReporterMock) EXPECT() *ReferenceReporterMock_Expecter {
	return &ReferenceReporterMock_Expecter{mock: &_m.Mock}
}

// ReferencedResources provides a mock function for the type ReferenceReporterMock
func (_mock *ReferenceReporterMock) ReferencedResources(merged any) []ConfigReference {
	ret := _mock.Called(merged)

	if len(ret) == 0 {
		panic("no return value specified for ReferencedResources")
	}

	var r0 []ConfigReference
	if returnFunc, ok := ret.Get(0).(func(any) []ConfigReference); ok {
		r0 = returnFunc(merged)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ConfigReference)
		}
	}
	return r0
}

// ReferenceReporterMock_ReferencedResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReferencedResources'
type ReferenceReporterMock_ReferencedResources_Call struct {
	*mock.Call
}

// ReferencedResources is a helper method to define mock.On call
//   - merged any
func (_e *ReferenceReporterMock_Expecter) ReferencedResources(merged interface{}) *ReferenceReporterMock_ReferencedResources_Call {
	return &ReferenceReporterMock_ReferencedResources_Call{Call: _e.mock.On("ReferencedResources", merged)}
}

func (_c *ReferenceReporterMock_ReferencedResources_Call) Run(run func(merged any)) *ReferenceReporterMock_ReferencedResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ReferenceReporterMock_ReferencedResources_Call) Return(configReferences []ConfigReference) *ReferenceReporterMock_ReferencedResources_Call {
	_c.Call.Return(configReferences)
	return _c
}

func (_c *ReferenceReporterMock_ReferencedResources_Call) RunAndReturn(run func(merged any) []ConfigReference) *ReferenceReporterMock_ReferencedResources_Call {
	_c.Call.Return(run)
	return _c
}
